---
- hosts: local
  become: true
  vars_files:
    - ../group_vars/all.yml
  tags: [new_machine, common]
  tasks:
  - name: Update pacman database (Arch)
    community.general.pacman:
      update_cache: true

  - name: Install common packages
    community.general.pacman:
      name: "{{ common_packages }}"
      state: present
  - name: Create aur_build user  
    user:
      name: aur_builder
      home: /home/aur_builder
      shell: /bin/nologin
      create_home: yes
  - name: Update sudoers file foe aur_user
    lineinfile:
      path: /etc/sudoers.d/99_aur_builder
      state: present
      line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
      mode: 0644
      validate: /usr/sbin/visudo -cf %s
      create: yes
  - name: Install packages from AUR
    become: yes
    become_user: aur_builder
    kewlfft.aur.aur:
      name: "{{ common_packages_aur }}"
      state: present
      use: yay
  - name: Download yubico authenticator appimage
    become: yes 
    get_url:
      url: "{{ yubico_authenticator_url }}"
      dest: "/tmp/yubico_authenticator.tar.gz"

  - name: Create yubico authenticator opt directory
    file:
        path: /opt/yubico-authenticator
        state: directory
        owner: root
        group: root
        mode: '0755'

  - name: Extract tar.gz into /opt/yubico-authenticator (no subdirectory)
    ansible.builtin.unarchive:
      src: "/tmp/yubico_authenticator.tar.gz"
      dest: "/opt/yubico-authenticator"
      remote_src: true
      extra_opts:
        - "--strip-components=1"

  - name: Delete yubico auth tarball from /tmp 
    ansible.builtin.file:
      path: /tmp/yubico_authenticator.tar.gz
      state: absent

  - name: Copy launcher config file for yubico-authenticator
    copy:
      src: ../files/yubico-authenticator.desktop
      dest: "/home/{{ user_name }}/.local/share/applications"

