---
- hosts: local
  become: true
  vars_files:
    - ../group_vars/all.yml
  tasks:
  - name: Update pacman database (Arch)
    community.general.pacman:
      update_cache: true

  - name: Install common packages
    community.general.pacman:
      name: "{{ common_packages }}"
      state: present
  - name: Create aur_build user and update the sudoers file 
    user:
      name: aur_builder
      home: /home/aur_builder
      shell: /bin/nologin
      create_home: yes
    lineinfile:
      path: /etc/sudoers.d/99_aur_builder
      state: present
      line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
      mode: 0644
      validate: /usr/sbin/visudo -cf %s
      create: yes
  - name: Install packages from AUR
    kewlfft.aur.aur:
    become: yes
    become_user: aur_builder
      name: "{{ common_packages_aur }}"
      state: present
      use: yay
  tags: [always, common]

