---
- name: Setup dotfiles with stow
  hosts: local
  vars_files:
    - ../group_vars/all.yml
  tags: [new_machine,dotfiles]
  tasks:
    - name: Clone dotfiles repo
      become_user: "{{ user_name }}"
      git:
        repo: "{{ _dotfiles_repo }}"
        dest: "{{ user_home }}/.dotfiles"
        update: yes
        force: true

    - name: Run stow to link all dotfiles
      become_user: "{{ user_name }}"
      args:
        chdir: "{{ user_home }}/.dotfiles"
      command: stow . --adopt -t "{{ user_home }}"

    - name: Restore working tree to HEAD (drop untracked/modified files in repo)
      ansible.builtin.command:
        cmd: git restore .
      args:
        chdir: "{{ user_home }}/.dotfiles"
      changed_when: "'Updated' in restore_out.stdout or 'Updated' in restore_out.stderr"
      register: restore_out
    
    - name: Remove HTTPS repo
      become_user: "{{ user_name }}"
      args:
        chdir: "{{ user_home }}/.dotfiles"
      command: git remote rm origin

    - name: Add SSH repo
      become_user: "{{ user_name }}"
      args:
        chdir: "{{ user_home }}/.dotfiles"
      command: git remote add origin {{ _dotfiles_repo_ssh }}
